repos:
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 5.1.4
  hooks:
  - id: isort
