baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "blog_out"

archetypeDir = "blog/archetypes"
contentDir = "blog/content"
data = "blog/data"
layoutDir = "blog/layouts"
staticDir = "blog/static"
themesDir = "blog/themes"
