[tool.bandit]
skips = ["B101"]

[tool.isort]
profile = "black"
src_paths = ["homeschool"]

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "allauth.account.signals",
    "dj_database_url",
    "django.*",
    "djstripe.*",
    "environ",
    "factory",
    "hashid_field.*",
    "ordered_model.*",
    "responses",
    "rollbar",
    "simple_history.*",
    "stripe",
    "test_plus.test",
    "waffle.*",
    "weasyprint",
    "whitenoise.middleware",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--nomigrations --disable-socket"
DJANGO_SETTINGS_MODULE = "project.testing_settings"
# filterwarnings =
# This warning is coming from dj-stripe 2.5.1 (Example)
#    ignore:.*The providing_args argument is deprecated\..*:DeprecationWarning
#    ignore:.*The providing_args argument is deprecated\..*:PendingDeprecationWarning
testpaths = [
    "homeschool",
]
